# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TodoTalk
  pod 'Toast-Swift', '~> 5.0.1'

  target 'TodoTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoTalkUITests' do
    # Pods for testing
  end

end
